     name: Check PR sync with main

     on:
       pull_request:
         types: [opened, synchronize]

     jobs:
       check-sync:
         runs-on: ubuntu-latest
         steps:
           - name: Checkout code
             uses: actions/checkout@v3

           - name: Fetch all branches
             run: git fetch origin main

           - name: Check if branch is up-to-date with main
             run: |
               git merge-base --is-ancestor origin/main HEAD || exit 1
             shell: bash
