name: Check PR Sync with Main

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  check-sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Fetch all branches
        run: git fetch --all

      - name: Check if branch is up-to-date with main
        run: |
          # Lấy commit mới nhất của main
          MAIN_LATEST=$(git rev-parse origin/main)

          # Kiểm tra xem commit của main có tồn tại trong nhánh hiện tại
          if git merge-base --is-ancestor $MAIN_LATEST HEAD; then
            echo "Branch is up-to-date with main."
          else
            echo "Branch is NOT up-to-date with main. Please rebase or merge main into your branch."
            exit 1
          fi
        shell: bash
